[package]
name = "ms-mdm"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
xml = "0.8.10"
yaserde = { version = "0.10.0", features = ["yaserde_derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
