name: 🐞 Bug Report
description: Report a reproducible bug or regression
labels:
  - kind/bug
  - status/needs-triage

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/mattrax/mattrax/issues?q=is%3Aissue) about this problem first.
        2. Please include instructions and/or a video on how to reproduce the problem.
        4. Remember to follow our community guidelines and be friendly.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
