AWSTemplateFormatVersion: 2010-09-09

Parameters:
  IntuneEmailCallbackURL:
    Type: String
    Default: ""
    Description: The URL of the webhook callback for Intune events. In the form 'https://sns:todo@domain.com/api/webhook/sns'

Outputs:
  VercelAccessKeyId:
    Description: AWS_ACCESS_KEY_ID
    Value: !Ref VercelAccessKey

  VercelAccessKeySecret:
    Description: AWS_SECRET_ACCESS_KEY
    Value: !GetAtt VercelAccessKey.SecretAccessKey

Conditions:
  ShouldSetCallbackURL: !Not
    - !Equals 
      - !Ref IntuneEmailCallbackURL
      - ""

Resources:
  ForgeData:
    Type: AWS::S3::Bucket

  VercelUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${ForgeData}/*
        
        - PolicyName: SES
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: "*" # TODO: Props restrict this down to the correct domain
                # TODO: Restrict `ses:FromAddress` and `ses:FromDisplayName` for better security

  VercelAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref VercelUser
  
  # Intune doesn't have a "subscribe to devices" endpoint so we abuse it's email callback feature.

  IntuneCallbackReceiptRuleSet: # TODO: This has to be manually set as enabled in the dashboard
    Type: 'AWS::SES::ReceiptRuleSet'

  IntuneCallbackQueue:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        !If
          - ShouldSetCallbackURL
          - 
            - Protocol: https
              Endpoint: !Ref IntuneEmailCallbackURL
          - !Ref "AWS::NoValue"

  IntuneCallbackReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Ref IntuneCallbackReceiptRuleSet
      Rule:
        Name: bridge-to-sns
        Enabled: true
        ScanEnabled: false
        TlsPolicy: Optional
        Recipients:
         - intune@internal.mattrax.app
        Actions:
         - SNSAction:
            Encoding: UTF-8
            TopicArn: !Ref IntuneCallbackQueue

